---
title: "DSD GitLab Report"
author: "MAJ Munson"
date: "`r Sys.Date()`"
output: html_document
params:
  org:
    label: "DSD organizations"
    value: netc-dsd
    input: select
    choices: [netc-dsd, dsc-monterey, dsc-pgh, dsc-phoenix, pmo]
resource_files:
- .Renviron
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r source, include=FALSE}
library(gitlabr)
library(dplyr)
library(tidyr)
library(forcats)

# Connect to API ----------------------------------------------------------

# DSD - GitLab 
dsd_url <- "https://gitlab.devforce.disa.mil/netc-dsd"

# connect as a fixed user to a GitLab instance for the session
gitlabr::set_gitlab_connection(
  gitlab_url = dsd_url,
  private_token = Sys.getenv("GITLAB_COM_TOKEN"))

# Get Projects ------------------------------------------------------------

# All DevForce GitLab Projects
gl_projects <- 
  gitlabr::gl_list_projects(
    max_page = 200, 
    owner = TRUE) %>% 
  janitor::clean_names()

# Select DSD Projects -----------------------------------------------------

# select DSD projects
dsd_projects <- gl_projects %>%
  dplyr::filter(namespace_id == 1932 |
                  namespace_id == 4209 |
                  namespace_id == 3957 |
                  namespace_id == 2746 |
                  namespace_id == 2456 |
                  namespace_id == 3294)

breakdowns <- dsd_projects %>%
  dplyr::group_by(namespace_full_path) %>%
  dplyr::count()

sep <- dsd_projects %>%
  tidyr::separate(
    col = namespace_full_path,
    sep = "/",
    into = c("L1", "L2", "L3"),
    remove = FALSE,
    convert = TRUE) %>%
  dplyr::mutate(
    L2 = dplyr::if_else(
      condition = is.na(L2),
      true = L1,
      false = L2),
    L3 = dplyr::if_else(
      condition = is.na(L3),
      true = L2,
      false = L3))

sep_break <- sep %>%
  dplyr::group_by(L2) %>%
  dplyr::count()
```

```{r chart, include=FALSE}
# Project Chart -----------------------------------------------------------

# DSD GitLab Repos
dsd_gl_projects <- sep %>%
  dplyr::mutate(
    last_activity_at = lubridate::as_date(last_activity_at),
    created_at = lubridate::as_date(created_at)) %>%
  dplyr::arrange(-dplyr::desc(created_at)) %>%
  dplyr::mutate(
    proj_ord = dplyr::row_number()) %>%
  dplyr::relocate(proj_ord, .before = id) %>%
  dplyr::mutate(
    name = forcats::fct_reorder(name, proj_ord),
    name = forcats::fct_rev(name)) %>%
  dplyr::filter(L2 == params$org)

dsd_chart <- dsd_gl_projects %>% 
  ggplot2::ggplot(ggplot2::aes(y = name)) +
  ggplot2::geom_segment(
    ggplot2::aes(x = created_at,
                 xend = last_activity_at,
                 y = name, yend = name),
    color = "royalblue1",
    lineend = "round",
    size = 2) +
  ggplot2::geom_vline(
    ggplot2::aes(
      xintercept = as.numeric(Sys.Date())),
    color = "red", 
    linetype = "dashed") +
  ggplot2::annotate(
    geom = "text",
    x = Sys.Date() - 20,
    y = nrow(dsd_gl_projects) - 3,
    label = "Today",
    color = "red") +
  ggplot2::scale_x_date() +
  ggplot2::theme_bw() +
  ggplot2::labs(
    title = "DSD GitLab Code Repositories",
    x = "Year",
    y = "Project")
```

## DSD GitLab Projects

This document provides a run down of the DSD Gitlab Code Repositories across the Directorate.

The DSD GitLab is broken down into multiple subgroups that contain the following number of projects:

```{r echo=FALSE}
knitr::kable(x = sep_break,
             col.names = c("Organization", "Number of Projects"))
```

## Timeline of DSD GitLab Projects

```{r pressure, echo=FALSE, fig.width = 10, fig.height=20}
plotly::ggplotly(dsd_chart)
```
