---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny 
---

```{r libraries, include=FALSE}
library(gitlabr)
library(janitor)
library(dplyr)
library(tidyr)
library(forcats)
library(lubridate)
library(plotly)
library(shiny)
library(shinydashboard)
library(flexdashboard)
```

```{r access_api}
# # DSD - GitLab 
# dsd_url <- "https://gitlab.devforce.disa.mil/netc-dsd"
# 
# # connect as a fixed user to a GitLab instance for the session
# gitlabr::set_gitlab_connection(
#   gitlab_url = dsd_url,
#   private_token = Sys.getenv("GITLAB_COM_TOKEN"))
# 
# # All DevForce GitLab Projects
# gl_projects <- 
#   gitlabr::gl_list_projects(
#     max_page = 200, 
#     owner = TRUE) %>% 
#   janitor::clean_names()
```

```{r prep_data}
# # select, filter, format, clean raw data
# #   select - remove the majority of the columns for faster processing
# #   filter - out all user name spaces to leave only groups
# #   format - create L1/2/3 levels to assist is bucketing
# #   clean - general cleaning as required
# prep_gpa <- gl_projects %>% 
#   dplyr::select(
#     id:default_branch,
#     forks_count:namespace_full_path,
#     packages_enabled:visibility) %>% 
#   dplyr::filter(namespace_kind == "group") %>% 
#   tidyr::separate(
#     col = namespace_full_path, 
#     sep = "/", 
#     into = c("L1", "L2", "L3"), 
#     remove = FALSE, 
#     convert = TRUE) %>% 
#   dplyr::mutate(
#     L2 = dplyr::if_else(
#       condition = is.na(L2), 
#       true = L1, 
#       false = L2),
#     L3 = dplyr::if_else(
#       condition = is.na(L3), 
#       true = L2, 
#       false = L3)) %>% 
#   dplyr::mutate(
#     last_activity_at = lubridate::as_date(last_activity_at),
#     created_at = lubridate::as_date(created_at))
```



```{r}
# EoTR = data.frame(ReefName=c("Reef1", "Reef2", "Reef3", "Reef4"), 
#               MarineParkZone=c("Fished", "Fished", "Un-Fished", "Un-Fished"))

load("data/gpa_group_data.rda")

# L1
selectInput(inputId = "level_1",
            label = "GitLab Groups",
            choices = sort(unique(prep_gpa$L1)),
            selected = "netc-dsd")

# L2
# create filter for l2 entries
filter_level_1 <- reactive({
  prep_gpa %>% 
    dplyr::filter(L1 %in% input$level_1)
  
})

# display L2, based off L1 selection
observeEvent(filter_level_1(), {
  choices <- unique(filter_level_1()$L2)
  updateSelectInput(session = session,
                    inputId = "level_2",
                    choices = choices)

})

# Display L2 options
selectInput(inputId = "level_2",
            label = "GitLab Sub-Groups",
            choices = NULL)

# L3
# create filter for l3 entries
filter_level_2 <- reactive({
  prep_gpa %>% 
    dplyr::filter(L2 %in% input$level_2)
  
})

# display L2, based off L1 selection
observeEvent(filter_level_2(), {
  choices <- unique(filter_level_2()$L3)
  updateSelectInput(session = session,
                    inputId = "level_3",
                    choices = choices)

})

# Display L2 options
selectInput(inputId = "level_3",
            label = "GitLab Super-Sub-Groups",
            choices = NULL)



# Project Picker
# create filter for l3 entries
filter_level_3 <- reactive({
  prep_gpa %>% 
    dplyr::filter(L3 %in% input$level_3)
  
})

# display Projects, based off L3 selection
observeEvent(filter_level_3(), {
  choices <- unique(filter_level_3()$name)
  updateSelectInput(session = session,
                    inputId = "project_name",
                    choices = choices)

})

# Display Project options
selectInput(inputId = "project_name",
            label = "Project Picker",
            choices = NULL)


# 
# https://stackoverflow.com/questions/55712090/is-there-a-way-to-select-all-of-a-sub-list-with-shiny-selectinput
# 
# https://stackoverflow.com/questions/45975959/create-reactive-selectinput-flexdashboard-with-shiny












# L1_L2 <- reactive({
#   
#   prep_gpa %>% 
#     dplyr::filter(L1 == input$L1)
# 
# })
# 
# renderUI({
#   
#   selectInput(
#     inputId = "L2", 
#     label = "GitLab Sub-Group", 
#     choices = L1_L2()$L2)
#   
#   })
# 
# L2_L3 <- reactive({
#   
#   prep_gpa %>% 
#     dplyr::filter(L1 == input$L1 |
#                     L2 == input$L2)
# })
# 
# renderUI({
#   
#   selectInput(
#     inputId = "L3", 
#     label = "GitLab Sub-Group", 
#     choices = L2_L3()$L3)
#   
#   })




# 
# 
# 
# zone.choices = reactive({
#   if (input$Zone=="All"){
#   EoTR
#   }else{
#   EoTR %>%
#   filter(MarineParkZone==input$Zone)}
# })
# 
# 
# renderUI({selectInput("Reef", label = "Priority Reef:",
#         choices = zone.choices()$ReefName, selected = "Reef1")})

```